#!/bin/bash

SIP_USERNAME=$1
SIP_DOMAIN=$2
CCOUNT=${3:-1}
CPS=${4:-1}

if [ "${SIP_USERNAME}" == "" ]; then
  echo "Missing SIP_USERNAME. Exit"
  exit 1
fi

if [ "${SIP_DOMAIN}" == "" ]; then
  echo "Missing SIP_DOMAIN. Exit"
  exit 1
fi

voip_perf "sip:${SIP_USERNAME}@${SIP_DOMAIN}" \
	      --method="INVITE" \
	      --local-port=5050 \
        --caller-id="1??????????" \
        --interval=1 \
        --count=${CCOUNT} \
        --call-per-second=${CPS} \
	      --window=1000 \
        --timeout=7200 \
        --verbose
        #--proxy ${PROXY}
