#!/bin/sh
cat << EOF
Usage: run this docker image with name of script and its arguments.

example:

docker run --rm --network=host voip_perf client dst_number dst_ip call_id call_count

Available scripts:
------------------
client          - dial <sip:destination_number@domain>, args: dst_number, dst_domain, call_count, CPS
client_tls      - dial over TLS (tls/certificate.pem, tls/key.pem, tls/ca_list.pem)
server          - run server mode on local_port with call duration
EOF